services:
  web-api-run-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_PHASE: run_dev
        API_DOMAIN: localhost
        API_PORT: 3000
    volumes:
      # 두번째 volume:
      #   -v single argument: 해당 위치에 이름 없는(anonymous) 볼륨을 마운트 - 컨테이너가 삭제되어도 살아있는 데이터
      #     이미 이미지의 해당 위치에 데이터가 존재할 경우, 해당 데이터를 볼륨으로 그대로 감싸는 듯 함.
      #     이 경우: 특정 플렛폼에서 빌드(이 경우 도커 컨테이너의 리눅스에서의 빌드(Dockerfile 을 통해))한
      #     js package 를 사용해야 정상 동작하므로, 앞선 첫번째 마운트에서 package 디렉토리만 제외하기 위해 사용
      - ./soc-api:/root/soc-api
      - /root/soc-api/node_modules
    ports:
      - "3000:3000"
